Ensure role_path is defined in _look_for_role_files
The _look_for_role_files method looks for Ansible files
under a possible role_path, as returned by _rolepath().

But this method may return None in some circumstances.

This caused ansible-lint to crash with:
  File "ansiblelint/utils.py", line 166, in _look_for_role_files
    thpath = os.path.join(_rolepath(basedir, role), th, 'main.yml')
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

Now we proceed with the files lookup only if role_path is defined.