Fixed outdated test dependencies
- Updates dependencies
- Includes pip-compile as part of linting, to assure they are less
  likely to rot.
- avoid running each job twice on changes made to branches
- removes hashed dependencies because mixed use caused CI failures on
  docs job:

ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not: