Allow snake_case module names for rules
PEP8 states that modules (files) should be named with snake_case not
CamelCase. Following this convention for AnsibleLint rules causes a
traceback:

    Traceback (most recent call last):
      File "ansible-lint", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "bin/ansible-lint", line 110, in <module>
        sys.exit(main(sys.argv[1:]))
      File "bin/ansible-lint", line 79, in main
        rules.extend(RulesCollection.create_from_directory(rulesdir))
      File "lib/ansiblelint/__init__.py", line 136, in create_from_directory
        result.rules = ansiblelint.utils.load_plugins(os.path.expanduser(rulesdir))
      File "lib/ansiblelint/utils.py", line 45, in load_plugins
        obj = getattr(mod, pluginname)()
    AttributeError: 'module' object has no attribute 'task_has_tag'

This patch checks the initial capitalisation of the module name, if it's
lowercase then the module name is converted to CamelCase before
attempting to load that class.