Avoid installation failure with newer setuptools
Implement workaround for avoiding installation errors on system with
newer setuptools

AttributeError: 'SpecifierSet' object has no attribute 'split'

Longer term we will have to refactor setup.py which is the root
of all evil.

Fixes: #590
Signed-off-by: Sorin Sbarnea <ssbarnea@redhat.com>